### ISSUE TITLE
会場手配

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt05docs#2]

**Comment by denari** [comment]
:spicelife: 社をお借りすることができました、やったね 🎉

**Comment by unasuke** [comment]
## KPT

### Problem
- プロジェクターの入力切替
- コンセントが少ない

### Try
- 変換コネクタを使い入力系統を1つにまとめる
  - mac勢多いならappleTVありか？
- コンセント延長ケーブルもうちょっとふやす
