### ISSUE TITLE
Connpassでのイベント作成

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt05docs#5]

**Comment by denari** [comment]
こんな会話をした

```
nkmrya [4:26 PM]  
そういえばDoorkeeperの代替どれにする？

denari [4:26 PM]  
connpassを検討中かな。(こだわりはない。)

denari [4:27]  
kosen10s.connpass.com
これを以前たまたま作っていたからというだけの理由
```

**Comment by pndcat** [comment]
connpass にしよう！

**Comment by denari** [comment]
文章done

---

# 2010年に選択を間違えた人たちでLT会！

本イベントは2010年に高専に入学された高専出身者で集まってLT会をするものです

# 持ってくるものまとめ
- 参加費 (本会自体は1000円あれば足りるかと思います。)
- 二次会の費用 (現在計画中)
- 自己紹介スライド資料
- LTスライド資料 (発表する人だけ)

# イベントの大まかな流れ

## 自己紹介(参加者全員)

初顔合わせの方もいるかと思うので、自己紹介をしていただきます。
プレゼン資料などはあっても無くてもOKですが、ご用意を推奨します。

時間は5分以内とします

## フリー発表(時間制限なし、任意参加)

自分の話したい内容について、好きなだけLTをしてもらいます。
LT希望者が多い場合は、ある程度短めにするようお願いするかもしれません。

また、LTをしていない参加者の方も、聞きたい人だけが聞く形式で。

# 参加費について

今回のイベントは会場と飲食物に費用がかかる都合上、参加費をいただくこととしています。参加費は会場にて頂戴します。

一人ひとりの参加費の最高額は大体1000円程度になるかと思います。

一人あたりの参加費を低くするためにも、是非ご友人に声をかけ、人数を増やして貰えればと思います。

# 質問・お問い合わせ

質問事項などは下記のTwitterアカウントにダイレクトメッセージをお送りいただくか、下記アドレスへメールをお願いします。

Twitter : @kosen10s
Mail : nct2010s(at)gmail.com

# 公式二次会!?

企画してくれる人を探し中...
続報をお待ちください。

**Comment by denari** [comment]
のこりやること
- [x] spice lifeの利用を公にするという確認 ( @unasuke  )
- [x] 会場キャパシティの確認 ( @unasuke  )
- [ ] ロゴ作成 ( @denari )

ロゴはなくても最悪9/1にはconnpassを公開する。

**Comment by unasuke** [comment]
## 会場キャパ

### 執務エリア側からみたかんじ

![img_1605](https://cloud.githubusercontent.com/assets/4487291/18043955/0e406310-6e06-11e6-9210-a497b3712dcb.JPG)

### 入り口から見た感じ

![img_1607](https://cloud.githubusercontent.com/assets/4487291/18043954/0e3ee9cc-6e06-11e6-9937-67c5fdd14fc8.JPG)

椅子は20席でそれ以上はないかな

**Comment by c-bata** [comment]
> 高専をついこの間卒業したイケてる人たちでLT会！

そろそろ使えなくなってきたかも

**Comment by unasuke** [comment]
利用については別にいいんでないかなと思うんでチェックした

**Comment by denari** [comment]
http://kosen10s.connpass.com/event/38953/
