### ISSUE TITLE
懇親会の企画

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt05docs#6]

**Comment by denari** [comment]
やってくれる神を募集しよう

**Comment by denari** [comment]
やった。金の蔵20人18:30より予約 :done:

**Comment by pndcat** [comment]
issue 閉じたあとにすまぬ．

orisano くん，会の途中で沖縄に帰っちゃうので懇親会参加できず〜
あと，たしかとちくじも途中で抜けるから参加しないはず

**Comment by denari** [comment]
一応聞いた、前日と当日に人数の前後の旨を確認しないとならないので #lt05 channelにもremind設定したのでこのissueはもうcloseのままで。
