### ISSUE TITLE
当日の運営手伝いマンにやってもらうことをリスト化

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt05docs#7]
# 人を割り振るやつ
- 会場でよしな動いてもらえる人 ( unasuke しか無理 )
- 懇親会までの案内・懇親会仕切り ( denariやりました )
- 飲食物調達仕切り
# 人を割り振ってないやつ
- 飲食物調達(2人)

**Comment by denari** [comment]
@channel 飲み物の調達手伝ってくれる人募集中。イケメンカモン 

```
でなりからお金を受け取って、そのお金をつかって本会中に飲むジュースや食べるお菓子なんかを「センスで」選んでくる仕事。

担当になってくれた人の他に、買い出しに行く際会場にいた人を2人ぐらい勝手に連れて行ってもらって、3人程度で買いに行ってもらうため、力仕事というわけでもない
```

**Comment by denari** [comment]
リアクションがこないので当日早く来てくれた人に任せます。 close
