### ISSUE TITLE
当日の必要物品リストの作成

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt05docs#8]
- [ ] 名札
- [ ] 名札ケース
- [ ] お金(会場内飲食物一時払い用)

**Comment by denari** [comment]
@unasuke どうせある気がするけど

プロジェクターって会場にあるよね。
あとついでに対応アダプタを教えてほしく。

**Comment by unasuke** [comment]
プロジェクターあり〼

**対応端子**
- HDMI
- VGA

VGA2ThunderboltはあるんだけどHDMI2Thunderboltはないかも……

**Comment by denari** [comment]
comment updated
